# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fence < Formula
  desc "Lightweight, container-free sandbox for running commands with network and filesystem restrictions"
  homepage "https://github.com/Use-Tusk/fence"
  version "0.1.29"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Use-Tusk/fence/releases/download/v0.1.29/fence_0.1.29_Darwin_x86_64.tar.gz"
      sha256 "5c2ca28371a3301382ef4ccf9e6d4d274178e1c1f15afa9ec5fef10c23cfefce"

      def install
        bin.install "fence"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Use-Tusk/fence/releases/download/v0.1.29/fence_0.1.29_Darwin_arm64.tar.gz"
      sha256 "1526421369ec5945d07a0829f91898a20ffd0bf6474c8f5805f2e5fb5da35a14"

      def install
        bin.install "fence"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Use-Tusk/fence/releases/download/v0.1.29/fence_0.1.29_Linux_x86_64.tar.gz"
      sha256 "3c0f0a1feda2b57d2c58fc400611adcfe938c6327ac500e23d99aba145d4826e"
      def install
        bin.install "fence"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Use-Tusk/fence/releases/download/v0.1.29/fence_0.1.29_Linux_arm64.tar.gz"
      sha256 "ba6bedeae07d49daa0bbf12b158ba3b2b5d27491c5379da07f2c93ff66eed1c8"
      def install
        bin.install "fence"
      end
    end
  end

  test do
    system "#{bin}/fence", "--version"
  end
end
