# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tusk < Formula
  desc "CLI for recording and replaying API traffic tests with Tusk Drift"
  homepage "https://github.com/Use-Tusk/tusk-drift-cli"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Use-Tusk/tusk-drift-cli/releases/download/v0.2.2/tusk-drift-cli_0.2.2_Darwin_x86_64.tar.gz"
      sha256 "4413d6b63ce627fef48a497943a1a1fec6d876825eee3c2c80c50baa144fac3f"

      define_method(:install) do
        bin.install "tusk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Use-Tusk/tusk-drift-cli/releases/download/v0.2.2/tusk-drift-cli_0.2.2_Darwin_arm64.tar.gz"
      sha256 "413b604da170c6a44149855efa342c768401cc6d0c1bb090a81304b933131eaa"

      define_method(:install) do
        bin.install "tusk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Use-Tusk/tusk-drift-cli/releases/download/v0.2.2/tusk-drift-cli_0.2.2_Linux_x86_64.tar.gz"
      sha256 "7707bd28a0801e6664879e0e6388b8c7fe967bfa3d40065628a3f31c64155886"
      define_method(:install) do
        bin.install "tusk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Use-Tusk/tusk-drift-cli/releases/download/v0.2.2/tusk-drift-cli_0.2.2_Linux_arm64.tar.gz"
      sha256 "9ba80751540f8d2b978bd4989f5d7efb4a5c1eaf7c21e52be467df5b58c59a75"
      define_method(:install) do
        bin.install "tusk"
      end
    end
  end

  test do
    system "#{bin}/tusk", "--version"
  end
end
