# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tusk < Formula
  desc "CLI for recording and replaying API traffic tests with Tusk Drift"
  homepage "https://github.com/Use-Tusk/tusk-drift-cli"
  version "0.1.60"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Use-Tusk/tusk-drift-cli/releases/download/v0.1.60/tusk-drift-cli_0.1.60_Darwin_x86_64.tar.gz"
      sha256 "69084ea4b789319297a72bfc71871d5651f1f791245d848ee3a127efa347be87"

      define_method(:install) do
        bin.install "tusk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Use-Tusk/tusk-drift-cli/releases/download/v0.1.60/tusk-drift-cli_0.1.60_Darwin_arm64.tar.gz"
      sha256 "c9ca13a8bfd0ecaa41a5c7389fc4e668cfa5ecbc658fc74532b6471841c2e539"

      define_method(:install) do
        bin.install "tusk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Use-Tusk/tusk-drift-cli/releases/download/v0.1.60/tusk-drift-cli_0.1.60_Linux_x86_64.tar.gz"
      sha256 "d7736a85a758e9cc27edf128bc0a085e8ac9c7856f6bcdd2d8db5b931f094cf1"
      define_method(:install) do
        bin.install "tusk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Use-Tusk/tusk-drift-cli/releases/download/v0.1.60/tusk-drift-cli_0.1.60_Linux_arm64.tar.gz"
      sha256 "2c1f61f8ec26ae239c127fca36bd8d4aa9a5882dcaa9ddb88b4412fe97141f5c"
      define_method(:install) do
        bin.install "tusk"
      end
    end
  end

  test do
    system "#{bin}/tusk", "--version"
  end
end
