# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tusk < Formula
  desc "CLI for recording and replaying API traffic tests with Tusk Drift"
  homepage "https://github.com/Use-Tusk/tusk-cli"
  version "0.2.14"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Use-Tusk/tusk-cli/releases/download/v0.2.14/tusk-cli_0.2.14_Darwin_x86_64.tar.gz"
      sha256 "0ae50195d0f2857f055b933cababb37daa575d65cf174cd0dcd81bc3df8cba65"

      define_method(:install) do
        bin.install "tusk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Use-Tusk/tusk-cli/releases/download/v0.2.14/tusk-cli_0.2.14_Darwin_arm64.tar.gz"
      sha256 "d6004b51e8c5c31fd19cef131633332aadcc2a847b96a483646c714831161b25"

      define_method(:install) do
        bin.install "tusk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Use-Tusk/tusk-cli/releases/download/v0.2.14/tusk-cli_0.2.14_Linux_x86_64.tar.gz"
      sha256 "b423b740bcb854906571bde96130eae8dfff2c63032523dbaecfce574bba4f40"
      define_method(:install) do
        bin.install "tusk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Use-Tusk/tusk-cli/releases/download/v0.2.14/tusk-cli_0.2.14_Linux_arm64.tar.gz"
      sha256 "0c34a552f17437947309b2a2ce62992e5105b1d009111eaeca2bae672f4f6518"
      define_method(:install) do
        bin.install "tusk"
      end
    end
  end

  test do
    system "#{bin}/tusk", "--version"
  end
end
